export const ANGER_JOURNAL_PROMPTS = [
  "What triggered my anger today?",
  "How did I physically feel when I was angry?",
  "What thoughts were going through my mind when I felt angry?",
  "Did I express my anger, or did I keep it bottled up?",
  "How did I react to my anger?",
  "Did my anger affect my relationships with others?",
  "What could I have done differently when I felt angry?",
  "What coping mechanisms did I use to deal with my anger?",
  "Was my anger proportional to the situation?",
  "Did my anger stem from underlying emotions, such as fear or hurt?",
  "How does my anger impact my mental and physical health?",
  "What patterns do I notice in my anger triggers?",
  "Have I noticed any recurring themes in my anger episodes?",
  "What are some healthy ways I can release my anger?",
  "Did I communicate my anger effectively?",
  "What are some positive lessons I can learn from my anger?",
  "How can I practice forgiveness and let go of past anger?",
  "What are some affirmations I can use to manage my anger?",
  "What boundaries can I set to prevent anger-inducing situations?",
  "What activities or hobbies help me relax and unwind when I'm feeling angry?",
  "Did I apologize or make amends for any actions I took in anger?",
  "How can I express my anger constructively without hurting others?",
  "What support systems do I have in place to help me cope with my anger?",
  "How can I practice self-compassion when I'm feeling angry?",
  "What role does anger play in my life, and how do I want to change that?",
  "What triggers from my past might be influencing my current anger?",
  "How can I practice mindfulness to become more aware of my anger triggers?",
  "What strategies can I use to prevent future anger outbursts?",
  "What are some healthy outlets for my anger, such as exercise or art?",
  "How can I challenge any negative beliefs or thought patterns that contribute to my anger?",
  "What are some alternative ways I can express my emotions besides anger?",
  "Did I seek professional help or guidance for my anger?",
  "How can I cultivate gratitude and positivity to counteract feelings of anger?",
  "What boundaries can I set with others to protect myself from their anger?",
  "Did I practice patience and understanding in situations that triggered my anger?",
  "How can I practice assertiveness to communicate my needs without resorting to anger?",
  "What self-care practices can I incorporate into my routine to manage my anger?",
  "Did I take time to cool off and reflect before reacting in anger?",
  "How can I use journaling as a tool to track my progress in managing my anger?",
  "What are some healthy ways I can release pent-up anger, such as journaling or talking to a friend?",
  "Did I express gratitude for the positive aspects of my life, even when I was feeling angry?",
  "How can I practice empathy and understanding towards others, even when they provoke my anger?",
  "What boundaries do I need to establish to protect myself from toxic relationships that trigger my anger?",
  "Did I take responsibility for my actions and words when I was angry, or did I blame others?",
  "How can I cultivate patience and resilience to navigate challenging situations without succumbing to anger?",
  "What positive affirmations or mantras can I repeat to myself when I feel anger rising?",
  "How can I use visualization techniques to imagine myself responding calmly and assertively in situations that typically provoke anger?",
  "Did I take breaks throughout the day to check in with myself and assess my emotional state, especially when I felt anger brewing?",
  "What role does forgiveness play in releasing anger and moving forward?",
  "How can I practice acceptance of situations that I cannot change, rather than letting them fuel my anger?",
  "What lessons can I learn from past experiences of anger that can help me better manage my emotions in the future?",
  "Did I engage in activities that bring me joy and relaxation, even when I was feeling angry?",
  "How can I cultivate a sense of humor and perspective to lighten my mood and defuse anger?",
  "What positive habits or routines can I establish to promote emotional balance and reduce the likelihood of anger episodes?",
  "Did I express gratitude towards those who supported me or helped me navigate difficult emotions, even if I was feeling angry?",
  "How can I practice forgiveness towards myself for any mistakes or missteps made in moments of anger?",
  "What healthy boundaries can I set with myself to prevent self-criticism or rumination when I experience anger?",
  "Did I take time to reflect on the underlying emotions beneath my anger, such as fear, sadness, or frustration?",
  "How can I use mindfulness techniques, such as deep breathing or body scans, to ground myself and calm my mind when anger arises?",
  "What positive outlets for self-expression can I explore to channel my emotions in constructive ways, such as writing, art, or music?",
  "Did I engage in activities that promote relaxation and stress reduction, such as meditation, yoga, or spending time in nature, to alleviate feelings of anger?",
  "How can I practice self-compassion and gentleness towards myself, recognizing that experiencing anger is a natural part of being human?",
  "What healthy communication strategies can I use to express my needs and boundaries assertively, without resorting to aggression or hostility?",
  "Did I reach out to a trusted friend, family member, or therapist for support and guidance when I struggled with managing my anger?",
  "How can I cultivate a sense of gratitude for the lessons learned from moments of anger, recognizing them as opportunities for growth and self-awareness?",
  "What self-soothing techniques or rituals can I incorporate into my daily routine to provide comfort and solace during times of heightened emotion, such as taking a warm bath, listening to calming music, or practicing gentle movement?",
  "Did I practice patience and tolerance towards myself and others, recognizing that everyone experiences moments of anger and that forgiveness and understanding are essential components of healing and reconciliation?",
  "How can I cultivate a sense of empathy and compassion towards those who may have contributed to my feelings of anger, recognizing that everyone carries their own burdens and struggles?",
  "What healthy boundaries can I establish in my relationships to protect myself from recurring triggers of anger, such as setting limits on communication or avoiding certain environments or situations?",
  "Did I engage in activities that promote self-care and well-being, such as getting enough sleep, eating nutritious meals, and engaging in physical activity, to support my overall emotional health and resilience?",
  "How can I reframe my thoughts and perceptions about situations that provoke anger, adopting a more optimistic and balanced perspective that allows for greater understanding and acceptance?",
];
